window.translations = {
  en: {
    navTools: 'Tools',
    navLearn: 'Learn',
    navPricing: 'Pricing',
    navLogin: 'Login',
    heroTagline: 'From guesswork to confident real estate decisions',
    heroTitle: 'Solve your deal analysis in minutes, not spreadsheets for hours.',
    heroDescription: 'Get the exact tools and step-by-step guidance to evaluate flips, rentals, and financing with confidence.',
    heroStart: 'Start Free',
    heroExplore: 'Explore Tools',
    toolsTitle: 'Free resources',
    toolsDescription: 'Start with practical guides and core calculators at no cost.',
    toolFlipTitle: '🧮 Flip Calculator',
    toolFlipDesc: 'Estimate renovation spread, profit margin, and exit risk before you buy.',
    toolRentalTitle: '📈 Rental Cash Flow',
    toolRentalDesc: 'Project monthly cash flow with taxes, vacancies, and maintenance assumptions.',
    toolArvTitle: '🏠 ARV Estimator',
    toolArvDesc: 'Model comparable sales and confidence ranges to price your exit correctly.',
    toolHardMoneyTitle: '💰 Hard Money Analyzer',
    toolHardMoneyDesc: 'Understand lender points, interest carry, and blended deal cost in seconds.',
    tryTool: 'Open Tool',
    learnTitle: 'Beginner guides',
    learnDescription: 'Simple frameworks to avoid expensive mistakes in your first deals.',
    article1: 'How to Structure a Cash Offer',
    article2: 'What is a HELOC and when should you use it?',
    article3: 'How to Calculate ARV Correctly',
    pricingTitle: 'Free vs Premium',
    pricingDescription: 'Compare what you get today and what unlocks with Premium.',
    featureColumn: 'Feature',
    freePlan: 'Free',
    proPlan: 'Premium',
    feature1: 'Core calculators',
    freeFeature1: '2 tools',
    proFeature1: 'All tools + advanced modules',
    feature2: 'Learning content',
    freeFeature2: 'Basic guides',
    proFeature2: 'Full playbooks + templates',
    feature3: 'Project tracking',
    freeFeature3: 'Not included',
    proFeature3: 'Save and compare scenarios',
    feature4: 'Reports',
    freeFeature4: 'Manual notes',
    proFeature4: 'Exportable PDF reports',
    testimonialsTitle: 'Real success stories',
    testimonialsDescription: 'Investors using InvestorBlueprint to close better deals.',
    testimonial1Quote: '“I stopped overpaying for flips. The deal check workflow saved me from two bad offers in one month.”',
    testimonial1Name: '— Carlos M., Fix & Flip Investor',
    testimonial2Quote: '“The rental calculator gave us a clear buy/no-buy rule. We increased monthly cash flow by 18%.”',
    testimonial2Name: '— Laura & Ben, Rental Portfolio Owners',
    testimonial3Quote: '“Premium scenarios helped me negotiate financing with confidence and close faster.”',
    testimonial3Name: '— Diego R., BRRRR Operator',
    ctaTitle: 'Ready to scale your investing with clarity?',
    ctaDescription: 'Join Premium and unlock every calculator, report, and advanced framework.',
    ctaButton: 'Subscribe now',
    registerTitle: 'Create account',
    registerDesc: 'Sign up to activate your 30-day free trial.',
    registerName: 'Name',
    labelEmail: 'Email',
    labelPassword: 'Password',
    registerBtn: 'Create account',
    loginTitle: 'Sign in',
    loginDesc: 'If you come from “Start Free”, your 1-month trial is activated.',
    loginBtn: 'Sign in',
    accountTitle: 'My account',
    accountActiveSession: 'Active session with:',
    activatePaidBtn: 'Activate paid subscription',
    logoutBtn: 'Log out',
    toolBack: '← Back to tools',
    resultPrompt: 'Enter your numbers and click calculate.',
    calculate: 'Calculate',
    calculateDeal: 'Calculate Deal',
    flipTitle: '🧮 Flip Calculator',
    flipDesc: 'Underwrite flips with acquisition, rehab, financing, holding and sale assumptions. Use quick MAO checks and sensitivity ranges before submitting an offer.',
    flipPlanMode: 'Plan mode',
    flipFreePlan: 'Free · Basic',
    flipProPlan: 'Pro · Full underwriting',
    flipQuickDeal: 'Quick deal data',
    rentalTitle: '📈 Rental Cash Flow',
    rentalDesc: 'Fill your income and expenses to project monthly and annual cash flow.',
    rentalRent: 'Monthly Rent',
    rentalTaxes: 'Property Taxes / month',
    rentalInsurance: 'Insurance / month',
    rentalMaintenance: 'Maintenance / month',
    rentalManagement: 'Property Management / month',
    rentalVacancy: 'Vacancy Rate (%)',
    arvTitle: '🏠 ARV Estimator',
    arvDesc: 'Enter comparable sale prices and repair budget to estimate ARV and max offer.',
    arvComp1: 'Comparable Sale #1',
    arvComp2: 'Comparable Sale #2',
    arvComp3: 'Comparable Sale #3',
    arvRepairs: 'Estimated Repairs',
    hardMoneyTitle: '💰 Hard Money Analyzer',
    hardMoneyDesc: 'Fill in lender terms to estimate total financing cost and monthly interest carry.',
    hardMoneyLoan: 'Loan Amount',
    hardMoneyInterest: 'Interest Rate (%)',
    hardMoneyPoints: 'Lender Points (%)',
    hardMoneyMonths: 'Loan Term (months)',
    proRequiredAlert: 'This Pro module requires an active trial or paid subscription. Start from “Start Free”.'
  },
  es: {
    navTools: 'Herramientas',
    navLearn: 'Aprender',
    navPricing: 'Precios',
    navLogin: 'Ingresar',
    heroTagline: 'De adivinar a decidir con confianza en real estate',
    heroTitle: 'Resuelve tu análisis de operaciones en minutos, no en horas de hojas de cálculo.',
    heroDescription: 'Obtén herramientas exactas y guías paso a paso para evaluar flips, rentas y financiamiento con seguridad.',
    heroStart: 'Empezar Gratis',
    heroExplore: 'Ver Herramientas',
    toolsTitle: 'Recursos gratuitos',
    toolsDescription: 'Empieza con guías prácticas y calculadoras clave sin costo.',
    toolFlipTitle: '🧮 Calculadora de Flip',
    toolFlipDesc: 'Estima margen de renovación, ganancia y riesgo de salida antes de comprar.',
    toolRentalTitle: '📈 Flujo de Caja de Renta',
    toolRentalDesc: 'Proyecta flujo mensual con impuestos, vacancia y mantenimiento.',
    toolArvTitle: '🏠 Estimador de ARV',
    toolArvDesc: 'Modela comparables y rangos de confianza para fijar mejor tu salida.',
    toolHardMoneyTitle: '💰 Analizador de Hard Money',
    toolHardMoneyDesc: 'Calcula puntos, interés y costo total combinado del financiamiento.',
    tryTool: 'Abrir Herramienta',
    learnTitle: 'Guías para empezar',
    learnDescription: 'Frameworks simples para evitar errores costosos en tus primeras operaciones.',
    article1: 'Cómo estructurar una oferta en efectivo',
    article2: 'Qué es un HELOC y cuándo usarlo',
    article3: 'Cómo calcular ARV correctamente',
    pricingTitle: 'Gratis vs Premium',
    pricingDescription: 'Compara lo que obtienes hoy y lo que desbloqueas con Premium.',
    featureColumn: 'Funcionalidad',
    freePlan: 'Gratis',
    proPlan: 'Premium',
    feature1: 'Calculadoras principales',
    freeFeature1: '2 herramientas',
    proFeature1: 'Todas las herramientas + módulos avanzados',
    feature2: 'Contenido educativo',
    freeFeature2: 'Guías básicas',
    proFeature2: 'Playbooks completos + plantillas',
    feature3: 'Seguimiento de proyectos',
    freeFeature3: 'No incluido',
    proFeature3: 'Guardar y comparar escenarios',
    feature4: 'Reportes',
    freeFeature4: 'Notas manuales',
    proFeature4: 'Reportes PDF exportables',
    testimonialsTitle: 'Casos de éxito reales',
    testimonialsDescription: 'Inversionistas que usan InvestorBlueprint para cerrar mejores operaciones.',
    testimonial1Quote: '“Dejé de sobrepagar flips. El flujo de validación me salvó de dos malas ofertas en un mes.”',
    testimonial1Name: '— Carlos M., Inversionista Fix & Flip',
    testimonial2Quote: '“La calculadora de renta nos dio una regla clara de compra/no compra. Subimos 18% el flujo mensual.”',
    testimonial2Name: '— Laura y Ben, Dueños de portafolio de rentas',
    testimonial3Quote: '“Los escenarios Premium me ayudaron a negociar financiamiento con confianza y cerrar más rápido.”',
    testimonial3Name: '— Diego R., Operador BRRRR',
    ctaTitle: '¿Listo para escalar tu inversión con claridad?',
    ctaDescription: 'Únete a Premium y desbloquea cada calculadora, reporte y framework avanzado.',
    ctaButton: 'Suscribirme ahora',
    registerTitle: 'Crear cuenta',
    registerDesc: 'Regístrate para activar tu prueba gratis de 30 días.',
    registerName: 'Nombre',
    labelEmail: 'Correo',
    labelPassword: 'Contraseña',
    registerBtn: 'Crear cuenta',
    loginTitle: 'Iniciar sesión',
    loginDesc: 'Si entras desde “Start Free”, activas tu prueba por 1 mes.',
    loginBtn: 'Entrar',
    accountTitle: 'Mi cuenta',
    accountActiveSession: 'Sesión activa con:',
    activatePaidBtn: 'Activar suscripción de pago',
    logoutBtn: 'Cerrar sesión',
    toolBack: '← Volver a herramientas',
    resultPrompt: 'Ingresa tus datos y haz clic en calcular.',
    calculate: 'Calcular',
    calculateDeal: 'Calcular operación',
    flipTitle: '🧮 Calculadora de Flip',
    flipDesc: 'Analiza flips con supuestos de compra, rehab, financiamiento, holding y venta. Usa validaciones rápidas de MAO y escenarios antes de enviar una oferta.',
    flipPlanMode: 'Modo de plan',
    flipFreePlan: 'Gratis · Básico',
    flipProPlan: 'Pro · Underwriting completo',
    flipQuickDeal: 'Datos rápidos del deal',
    rentalTitle: '📈 Flujo de Caja de Renta',
    rentalDesc: 'Completa ingresos y gastos para proyectar flujo mensual y anual.',
    rentalRent: 'Renta mensual',
    rentalTaxes: 'Impuestos de propiedad / mes',
    rentalInsurance: 'Seguro / mes',
    rentalMaintenance: 'Mantenimiento / mes',
    rentalManagement: 'Administración / mes',
    rentalVacancy: 'Tasa de vacancia (%)',
    arvTitle: '🏠 Estimador de ARV',
    arvDesc: 'Ingresa ventas comparables y presupuesto de reparaciones para estimar ARV y oferta máxima.',
    arvComp1: 'Venta comparable #1',
    arvComp2: 'Venta comparable #2',
    arvComp3: 'Venta comparable #3',
    arvRepairs: 'Reparaciones estimadas',
    hardMoneyTitle: '💰 Analizador de Hard Money',
    hardMoneyDesc: 'Ingresa términos del prestamista para estimar costo total y carga mensual de intereses.',
    hardMoneyLoan: 'Monto del préstamo',
    hardMoneyInterest: 'Tasa de interés (%)',
    hardMoneyPoints: 'Puntos del prestamista (%)',
    hardMoneyMonths: 'Plazo del préstamo (meses)',
    proRequiredAlert: 'Este módulo Pro requiere prueba activa o suscripción de pago. Inicia desde “Start Free”.'
  }
};
