window.translations = {
  en: {
    navTools: 'Tools',
    navLearn: 'Learn',
    navPricing: 'Pricing',
    navLogin: 'Login',
    heroTagline: 'Interactive platform for modern investors',
    heroTitle: 'Build Wealth Through Real Estate, Smarter.',
    heroDescription: 'Analyze deals, compare scenarios, and learn professional investing frameworks in one place.',
    heroStart: 'Start Free',
    heroExplore: 'Explore Tools',
    toolsTitle: 'Tools Preview',
    toolsDescription: 'Real calculators for real decisions.',
    toolFlipTitle: '🧮 Flip Calculator',
    toolFlipDesc: 'Estimate renovation spread, profit margin, and exit risk before you buy.',
    toolRentalTitle: '📈 Rental Cash Flow',
    toolRentalDesc: 'Project monthly cash flow with taxes, vacancies, and maintenance assumptions.',
    toolArvTitle: '🏠 ARV Estimator',
    toolArvDesc: 'Model comparable sales and confidence ranges to price your exit correctly.',
    toolHardMoneyTitle: '💰 Hard Money Analyzer',
    toolHardMoneyDesc: 'Understand lender points, interest carry, and blended deal cost in seconds.',
    tryTool: 'Open Tool',
    learnTitle: 'Learn',
    learnDescription: 'Mini guides to build investor judgment.',
    article1: 'How to Structure a Cash Offer',
    article2: 'What is a HELOC and when should you use it?',
    article3: 'How to Calculate ARV Correctly',
    pricingTitle: 'Pricing',
    pricingDescription: "Start free, upgrade when you're ready to scale.",
    freePlan: 'Free Plan',
    free1: 'Basic calculators',
    free2: 'Limited access',
    proPlan: 'Pro Plan',
    pro1: 'All tools included',
    pro2: 'Save projects',
    pro3: 'Export PDF reports',
    pro4: 'Scenario comparison'
  },
  es: {
    navTools: 'Herramientas',
    navLearn: 'Aprender',
    navPricing: 'Precios',
    navLogin: 'Ingresar',
    heroTagline: 'Plataforma interactiva para inversionistas modernos',
    heroTitle: 'Construye Riqueza con Bienes Raíces, de Forma Inteligente.',
    heroDescription: 'Analiza operaciones, compara escenarios y aprende marcos profesionales de inversión en un solo lugar.',
    heroStart: 'Empezar Gratis',
    heroExplore: 'Ver Herramientas',
    toolsTitle: 'Vista Previa de Herramientas',
    toolsDescription: 'Calculadoras reales para decisiones reales.',
    toolFlipTitle: '🧮 Calculadora de Flip',
    toolFlipDesc: 'Estima margen de renovación, ganancia y riesgo de salida antes de comprar.',
    toolRentalTitle: '📈 Flujo de Caja de Renta',
    toolRentalDesc: 'Proyecta flujo mensual con impuestos, vacancia y mantenimiento.',
    toolArvTitle: '🏠 Estimador de ARV',
    toolArvDesc: 'Modela comparables y rangos de confianza para fijar mejor tu salida.',
    toolHardMoneyTitle: '💰 Analizador de Hard Money',
    toolHardMoneyDesc: 'Calcula puntos, interés y costo total combinado del financiamiento.',
    tryTool: 'Abrir Herramienta',
    learnTitle: 'Aprender',
    learnDescription: 'Mini guías para desarrollar criterio inversionista.',
    article1: 'Cómo estructurar una oferta en efectivo',
    article2: 'Qué es un HELOC y cuándo usarlo',
    article3: 'Cómo calcular ARV correctamente',
    pricingTitle: 'Precios',
    pricingDescription: 'Empieza gratis y sube a Pro cuando quieras escalar.',
    freePlan: 'Plan Gratis',
    free1: 'Calculadoras básicas',
    free2: 'Acceso limitado',
    proPlan: 'Plan Pro',
    pro1: 'Todas las herramientas',
    pro2: 'Guardar proyectos',
    pro3: 'Exportar reportes PDF',
    pro4: 'Comparador de escenarios'
  }
};
