window.translations = {
  en: {
    navTools: 'Tools',
    navLearn: 'Learn',
    navPricing: 'Pricing',
    navLogin: 'Login',
    heroTagline: 'Interactive platform for modern investors',
    heroTitle: 'Build Wealth Through Real Estate, Smarter.',
    heroDescription: 'Analyze deals, compare scenarios, and learn professional investing frameworks in one place.',
    heroStart: 'Start Free',
    heroExplore: 'Explore Tools',
    toolsTitle: 'Tools Preview',
    toolsDescription: 'Real calculators for real decisions.',
    toolFlipTitle: '🧮 Flip Calculator',
    toolFlipDesc: 'Estimate renovation spread, profit margin, and exit risk before you buy.',
    toolRentalTitle: '📈 Rental Cash Flow',
    toolRentalDesc: 'Project monthly cash flow with taxes, vacancies, and maintenance assumptions.',
    toolArvTitle: '🏠 ARV Estimator',
    toolArvDesc: 'Model comparable sales and confidence ranges to price your exit correctly.',
    toolHardMoneyTitle: '💰 Hard Money Analyzer',
    toolHardMoneyDesc: 'Understand lender points, interest carry, and blended deal cost in seconds.',
    tryTool: 'Open Tool',
    learnTitle: 'Learn',
    learnDescription: 'Mini guides to build investor judgment.',
    article1: 'How to Structure a Cash Offer',
    article2: 'What is a HELOC and when should you use it?',
    article3: 'How to Calculate ARV Correctly',
    pricingTitle: 'Pricing',
    pricingDescription: 'Start with a 30-day free trial, then continue with a paid subscription.',
    freePlan: 'Free Trial',
    free1: 'Full access for 30 days',
    free2: 'Then upgrade to paid subscription',
    proPlan: 'Pro Plan',
    pro1: 'All tools included',
    pro2: 'Save projects',
    pro3: 'Export PDF reports',
    pro4: 'Scenario comparison',
    registerTitle: 'Create account',
    registerDesc: 'Sign up to activate your 30-day free trial.',
    registerName: 'Name',
    labelEmail: 'Email',
    labelPassword: 'Password',
    registerBtn: 'Create account',
    loginTitle: 'Sign in',
    loginDesc: 'If you come from “Start Free”, your 1-month trial is activated.',
    loginBtn: 'Sign in',
    accountTitle: 'My account',
    accountActiveSession: 'Active session with:',
    activatePaidBtn: 'Activate paid subscription',
    logoutBtn: 'Log out',
    toolBack: '← Back to tools',
    resultPrompt: 'Enter your numbers and click calculate.',
    calculate: 'Calculate',
    calculateDeal: 'Calculate Deal',
    flipTitle: '🧮 Flip Calculator',
    flipDesc: 'Underwrite flips with acquisition, rehab, financing, holding and sale assumptions. Use quick MAO checks and sensitivity ranges before submitting an offer.',
    rentalTitle: '📈 Rental Cash Flow',
    rentalDesc: 'Fill your income and expenses to project monthly and annual cash flow.',
    rentalRent: 'Monthly Rent',
    rentalTaxes: 'Property Taxes / month',
    rentalInsurance: 'Insurance / month',
    rentalMaintenance: 'Maintenance / month',
    rentalManagement: 'Property Management / month',
    rentalVacancy: 'Vacancy Rate (%)',
    arvTitle: '🏠 ARV Estimator',
    arvDesc: 'Enter comparable sale prices and repair budget to estimate ARV and max offer.',
    arvComp1: 'Comparable Sale #1',
    arvComp2: 'Comparable Sale #2',
    arvComp3: 'Comparable Sale #3',
    arvRepairs: 'Estimated Repairs',
    hardMoneyTitle: '💰 Hard Money Analyzer',
    hardMoneyDesc: 'Fill in lender terms to estimate total financing cost and monthly interest carry.',
    hardMoneyLoan: 'Loan Amount',
    hardMoneyInterest: 'Interest Rate (%)',
    hardMoneyPoints: 'Lender Points (%)',
    hardMoneyMonths: 'Loan Term (months)',
    proRequiredAlert: 'This Pro module requires an active trial or paid subscription. Start from “Start Free”.'
  },
  es: {
    navTools: 'Herramientas',
    navLearn: 'Aprender',
    navPricing: 'Precios',
    navLogin: 'Ingresar',
    heroTagline: 'Plataforma interactiva para inversionistas modernos',
    heroTitle: 'Construye Riqueza con Bienes Raíces, de Forma Inteligente.',
    heroDescription: 'Analiza operaciones, compara escenarios y aprende marcos profesionales de inversión en un solo lugar.',
    heroStart: 'Empezar Gratis',
    heroExplore: 'Ver Herramientas',
    toolsTitle: 'Vista Previa de Herramientas',
    toolsDescription: 'Calculadoras reales para decisiones reales.',
    toolFlipTitle: '🧮 Calculadora de Flip',
    toolFlipDesc: 'Estima margen de renovación, ganancia y riesgo de salida antes de comprar.',
    toolRentalTitle: '📈 Flujo de Caja de Renta',
    toolRentalDesc: 'Proyecta flujo mensual con impuestos, vacancia y mantenimiento.',
    toolArvTitle: '🏠 Estimador de ARV',
    toolArvDesc: 'Modela comparables y rangos de confianza para fijar mejor tu salida.',
    toolHardMoneyTitle: '💰 Analizador de Hard Money',
    toolHardMoneyDesc: 'Calcula puntos, interés y costo total combinado del financiamiento.',
    tryTool: 'Abrir Herramienta',
    learnTitle: 'Aprender',
    learnDescription: 'Mini guías para desarrollar criterio inversionista.',
    article1: 'Cómo estructurar una oferta en efectivo',
    article2: 'Qué es un HELOC y cuándo usarlo',
    article3: 'Cómo calcular ARV correctamente',
    pricingTitle: 'Precios',
    pricingDescription: 'Empieza con 30 días gratis y después continúa con una suscripción de pago.',
    freePlan: 'Prueba Gratis',
    free1: 'Acceso completo por 30 días',
    free2: 'Luego cambia a suscripción de pago',
    proPlan: 'Plan Pro',
    pro1: 'Todas las herramientas',
    pro2: 'Guardar proyectos',
    pro3: 'Exportar reportes PDF',
    pro4: 'Comparador de escenarios',
    registerTitle: 'Crear cuenta',
    registerDesc: 'Regístrate para activar tu prueba gratis de 30 días.',
    registerName: 'Nombre',
    labelEmail: 'Correo',
    labelPassword: 'Contraseña',
    registerBtn: 'Crear cuenta',
    loginTitle: 'Iniciar sesión',
    loginDesc: 'Si entras desde “Start Free”, activas tu prueba por 1 mes.',
    loginBtn: 'Entrar',
    accountTitle: 'Mi cuenta',
    accountActiveSession: 'Sesión activa con:',
    activatePaidBtn: 'Activar suscripción de pago',
    logoutBtn: 'Cerrar sesión',
    toolBack: '← Volver a herramientas',
    resultPrompt: 'Ingresa tus datos y haz clic en calcular.',
    calculate: 'Calcular',
    calculateDeal: 'Calcular operación',
    flipTitle: '🧮 Calculadora de Flip',
    flipDesc: 'Analiza flips con supuestos de compra, rehab, financiamiento, holding y venta. Usa validaciones rápidas de MAO y escenarios antes de enviar una oferta.',
    rentalTitle: '📈 Flujo de Caja de Renta',
    rentalDesc: 'Completa ingresos y gastos para proyectar flujo mensual y anual.',
    rentalRent: 'Renta mensual',
    rentalTaxes: 'Impuestos de propiedad / mes',
    rentalInsurance: 'Seguro / mes',
    rentalMaintenance: 'Mantenimiento / mes',
    rentalManagement: 'Administración / mes',
    rentalVacancy: 'Tasa de vacancia (%)',
    arvTitle: '🏠 Estimador de ARV',
    arvDesc: 'Ingresa ventas comparables y presupuesto de reparaciones para estimar ARV y oferta máxima.',
    arvComp1: 'Venta comparable #1',
    arvComp2: 'Venta comparable #2',
    arvComp3: 'Venta comparable #3',
    arvRepairs: 'Reparaciones estimadas',
    hardMoneyTitle: '💰 Analizador de Hard Money',
    hardMoneyDesc: 'Ingresa términos del prestamista para estimar costo total y carga mensual de intereses.',
    hardMoneyLoan: 'Monto del préstamo',
    hardMoneyInterest: 'Tasa de interés (%)',
    hardMoneyPoints: 'Puntos del prestamista (%)',
    hardMoneyMonths: 'Plazo del préstamo (meses)',
    proRequiredAlert: 'Este módulo Pro requiere prueba activa o suscripción de pago. Inicia desde “Start Free”.'
  }
};
